Added unit testing, snapshot testing, and one server integration test.
Dev-Stars/appointments pull request #5
Opened 2018-07-28 22:51 UTC by jmbice

Had to configure my yml and jest files to get it to work in circleci

2018-07-28 23:22 UTC, burkegg requested changes
There is some commented code, and two places where you have a tiny bit of code that doesn't hurt, but doesn't do anything either.  Your tests look great.  Nice work!

2018-07-28 23:22 UTC, burkegg commented on .circleci/config.yml
> +      # - run: sudo apt-get install mysql-server
Are you leaving this code in as a future option?

2018-07-28 23:22 UTC, burkegg commented on client/components/Appointment.jsx
>        businessId: Math.floor(Math.random() * Math.floor(100)),
If you're going for a number between 0 and 99 inclusive, I think you can leave off the second Math.floor.
i.e.  Math.floor(Math.random() * 100)

2018-07-28 23:22 UTC, burkegg commented on db/loadFake.js
>    const getRandom = max => Math.floor(Math.random() * Math.floor(max));
Unless you're putting in a decimal for max, I don't think Math.floor(max) is going to do anything but give you max.  So it definitely doesn't hurt anything to have it there, but I don't think it's doing anything.

2018-07-28 23:22 UTC, burkegg commented on tests/Appointment.test.js
> +// it('makeAppointment should make as forceUpdate', (done) => {
commented code.

2018-07-28 23:22 UTC, burkegg commented on tests/LevelOne.test.js
> +    it('getGuestCount should return an array of numbers, or null', () => {
This strikes me as a really nice test for both positive and negative results.

2018-07-28 23:22 UTC, burkegg commented on tests/LevelOne.test.js
> +//
commented code.

2018-07-29 13:44 UTC, jmbice commented on .circleci/config.yml
> +      # - run: sudo apt-get install mysql-server
I think I need this for my tests to run in circleci. My tests auto-load the fake data and test it.

2018-07-29 13:46 UTC, jmbice commented on client/components/Appointment.jsx
>        businessId: Math.floor(Math.random() * Math.floor(100)),
I did not know this!

2018-07-29 13:47 UTC, jmbice commented on db/loadFake.js
>    const getRandom = max => Math.floor(Math.random() * Math.floor(max));
I didn't have a firm understanding how this worked, this is most helpful.

2018-07-29 13:47 UTC, jmbice commented on tests/LevelOne.test.js
> +//
On it!

2018-07-29 13:47 UTC, jmbice commented on tests/LevelOne.test.js
> +    it('getGuestCount should return an array of numbers, or null', () => {
You're too kind sir.

2018-07-29 13:50 UTC, jmbice commented on .circleci/config.yml
> +      # - run: sudo apt-get install mysql-server
I am going to try it without, see if it's true. If not, i'll omit it on my next PR.

2018-07-29 14:55 UTC, merged